name: Emmanuel Berrido
favicon: null
layout_spectrum: 0.05488721514120698
typography_spectrum: 0.049088684376329184
title: Composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#e7f1fb'
    - '#6c6656'
    - '#b4aca2'
    - '#4e83d4'
  brandStrength: 0.9916443934198469
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
